name: diff checker

on:
  schedule:
    - cron: '0 23 * * *'
  # debug
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Check diff
        id: check-diff
        run: |
          go install github.com/suntong/html2md@latest
          curl https://go.dev/doc/faq | html2md -i -G | sed -n -e 106,2255p > original.md
          echo "add diff" >> original.md
          echo "diff=$(git diff --name-only original.md | wc -l | xargs )" >> $GITHUB_OUTPUT
          echo ${{ steps.check-diff.outputs.diff }}

      - name: Create a PR if diff exists
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.check-diff.outputs.diff != 0 }}
        run: |
          git switch -c feature/diff-$(date +'%Y-%m-%d')
          git add original.md
          gh pr create -t "Update site info" --body "Check the diff content"
